package:
  name: ros-melodic-rqt-reconfigure
  version: 0.5.3
source:
  git_url: https://github.com/ros-gbp/rqt_reconfigure-release.git
  git_rev: release/melodic/rqt_reconfigure/0.5.3-1
  folder: ros-melodic-rqt-reconfigure/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-melodic-catkin
    - ros-melodic-roslint
    - ros-melodic-rostest
    - setuptools
  run:
    - python
    - pyyaml
    - ros-melodic-dynamic-reconfigure
    - ros-melodic-python-qt-binding
    - ros-melodic-rospy
    - ros-melodic-rqt-console
    - ros-melodic-rqt-gui
    - ros-melodic-rqt-gui-py
    - ros-melodic-rqt-py-common
