package:
  name: ros-melodic-ros-environment
  version: 1.2.3
source:
  git_url: https://github.com/ros-gbp/ros_environment-release.git
  git_rev: release/melodic/ros_environment/1.2.3-1
  folder: ros-melodic-ros-environment/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-melodic-catkin
  run:
    - python
